.TH sysopctl 1 "October 2024" "sysopctl v0.1.0"
.SH NAME
sysopctl \- System Operations Control Command
.SH SYNOPSIS
.B sysopctl
[\fIcommand\fR] [\fIoptions\fR]
.SH DESCRIPTION
sysopctl is a command-line tool designed to help manage system services, resources, and processes on a Linux system.
.SH OPTIONS
.TP
.BR --help
Show usage information and examples.
.TP
.BR --version
Display the version of sysopctl.